version: '3.9'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    ports:
      - "3000:3000"
    platform: linux/amd64
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000/api
    stdin_open: true
    tty: true
    depends_on:
      - backend

#   mock:
#     build:
#       context: .
#       dockerfile: Dockerfile.mock
#     ports:
#       - "8001:8000"
#     volumes:
#       - ./mock:/app

  mysql:
    image: mysql:8.0
    container_name: rentflex-mysql
    ports:
      - "3307:3306"
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: rentflex
      MYSQL_USER: vivizhao
      MYSQL_PASSWORD: Ohsehun19981130!
    volumes:
      - mysql_data:/var/lib/mysql


  backend:
    build:
      context: .
      dockerfile: Dockerfile.backend
    container_name: rentflex-backend
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - mysql
    environment:
      - ENV=dev
    env_file:
      - ./backend/.env.dev

volumes:
  mysql_data:

