# frontend/Dockerfile.frontend
FROM node:18

WORKDIR /app
COPY ./frontend/package.json ./frontend/package-lock.json ./
RUN npm install

# COPY frontend/ /app/
# RUN npm run build

# # Use nginx to serve built static files
# FROM nginx:alpine
# COPY --from=0 /app/dist /usr/share/nginx/html
# COPY frontend/nginx.conf /etc/nginx/conf.d/default.conf

COPY ./frontend ./

EXPOSE 3000
CMD ["npm", "run", "dev"]
